chat_model_name: qwen3-max
embedding_model_name: text-embedding-v4
dashscope_api_key: "sk-ws-H.EEDIYIY.NF4W.MEUCIDauD6luTp3eIMUtbsKriuOQhZzHipenpz9xtCUNtT35AiEAoFGqJWgLqmRqWh9b54nHzW34lVmjqZdnH5jdQVx2Rnw"